# Generated by Django 2.2.19 on 2021-03-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=1024)),
                ('split_1', models.URLField()),
                ('split_2', models.URLField()),
                ('split_3', models.URLField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.UserInfo')),
            ],
            options={
                'ordering': ['file_id'],
                'unique_together': {('user_id', 'file_id')},
            },
        ),
    ]
