# Generated by Django 2.2.19 on 2021-03-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horcrux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uploaded', models.FileField(upload_to='files/')),
            ],
        ),
    ]
