# Generated by Django 2.2.19 on 2021-03-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horcrux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='split_1',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filedata',
            name='split_2',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filedata',
            name='split_3',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FileParts',
        ),
    ]
